# Generated by Django 4.1.2 on 2022-10-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='email',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='team',
            name='password',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
